// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbwcycrdmghffnlvewon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid2N5Y3JkbWdoZmZubHZld29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDEyMjQsImV4cCI6MjA2NzI3NzIyNH0.MjJaahsbIpv3yuDsToRfJO5WN2sW81J6336irVMx8nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});